function obs = getObservables( this )

% getObservables (SUMO)
%
%     This file is part of the Surrogate Modeling Toolbox ("SUMO Toolbox")
%     and you can redistribute it and/or modify it under the terms of the
%     GNU Affero General Public License version 3 as published by the
%     Free Software Foundation.  With the additional provision that a commercial
%     license must be purchased if the SUMO Toolbox is used, modified, or extended
%     in a commercial setting. For details see the included LICENSE.txt file.
%     When referring to the SUMO-Toolbox please make reference to the corresponding
%     publication.
%
% Contact : sumo@intec.ugent.be - www.sumo.intec.ugent.be
% Revision: $Rev: 6376 $
%
% Signature:
%	obs = getObservables( this )
%
% Description:
%	Returns observables

obs = { ...
	SimpleObservable( ...
		'C', ...
		'The cost parameter C of the SVM model', ...
		'SVMModel', ...
		@(x) extractField( x, 'config.regularizationParam' ) ), ...
	SimpleObservable( ...
		'kernelparam', ...
		'The kernel parameter of the SVM model', ...
		'SVMModel', ...
		@(x) extractField( x, 'config.kernelParams' ) ) ...
};
