Description of checkNewMiss
checkNewMiss
PURPOSE
% Method of KRG class
SYNOPSIS
function flagM=checkNewMiss(obj)
DESCRIPTION
% Method of KRG class
 L. LAURENT -- 07/08/2017 -- luc.laurent@lecnam.net
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
KRG % class for kriging/cokriging metamodel
RBF % class for RBF/GRBF metamodel
SVR % class for Support Vector Regression metamodel
xLS % Class for least-squares surrogate model
SOURCE CODE
%% Method of KRG class
% L. LAURENT -- 07/08/2017 -- luc.laurent@lecnam.net
%     GRENAT - GRadient ENhanced Approximation Toolbox
%     A toolbox for generating and exploiting gradient-enhanced surrogate models
%     Copyright (C) 2016-2017  Luc LAURENT <luc.laurent@lecnam.net>
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with this program.  If not, see <http://www.gnu.org/licenses/>.
%% Check if there is new missing data
% INPUTS:
% - none
% OUTPUTS:
% - flagM: true if some new data is missing
function flagM=checkNewMiss(obj)
flagM=false;
if ~isempty(obj.missData)
    flagM=obj.missData.onNew;
end
end