Description of dispTableTwoColumns
dispTableTwoColumns
PURPOSE
% Function display table with two columns (first must be text)
SYNOPSIS
function txt=dispTableTwoColumns(tableA,tableB,separator)
DESCRIPTION
% Function display table with two columns (first must be text)
 L. LAURENT -- 20/08/2017 -- luc.laurent@lecnam.net
CROSS-REFERENCE INFORMATION
This function calls:
Gfprintf % function for printing information on the command window (based on fprintf)
This function is called by:
critErrDisp % Compute error criteria and display
initMeta % Initialization of the surrogate model
showKernel % Method of KernMatrix class
cv % Method of KRG class
cv % Method of RBF class
cv % Method of SVR class
SOURCE CODE
%% Function display table with two columns (first must be text)
% L. LAURENT -- 20/08/2017 -- luc.laurent@lecnam.net
%     GRENAT - GRadient ENhanced Approximation Toolbox
%     A toolbox for generating and exploiting gradient-enhanced surrogate models
%     Copyright (C) 2016-2017  Luc LAURENT <luc.laurent@lecnam.net>
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with this program.  If not, see <http://www.gnu.org/licenses/>.
% INPUTS:
% - tableA: cell of strings
% - tableB: cell of strings, integers or float/double
% - separator: specific separator used (optional, default: whitespace)
% OUTPUTS:
% - none
%% function display table with two columns of text
function txt=dispTableTwoColumns(tableA,tableB,separator)
%size of every components in tableA
sizeA=cellfun(@numel,tableA);
maxA=max(sizeA);
%space after each component
spaceA=maxA-sizeA+2;
if nargin>2
    spaceTxt=separator;
else
    spaceTxt=' ';
end
txtOk=[];
%display table
for itT=1:numel(tableA)
    if ischar(tableB{itT})
        mask='%s%s%s\n';
    elseif isinteger(tableB{itT})
        mask='%s%s%i\n';
    else
        mask='%s%s%+5.4e\n';
    end
    %
    txtOk=[txtOk sprintf(mask,tableA{itT},[' ' spaceTxt(ones(1,spaceA(itT))) ' '],tableB{itT})];
end
if nargout==1
    txt=txtOk;
else
    Gfprintf(txtOk);
end
end