Description of Gfprintf
Gfprintf
PURPOSE
% function for printing information on the command window (based on fprintf)
SYNOPSIS
function nbT = Gfprintf(varargin)
DESCRIPTION
% function for printing information on the command window (based on fprintf)
% L. LAURENT -- 12/09/2016 -- luc.laurent@lecnam.net
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
checkRef % Method of GRENAT class
checkUpdate % Method of GRENAT class
conf % Method of GRENAT class
eval % Method of GRENAT class
initGRENAT % Method of GRENAT class
selfUpdate % Method of GRENAT class
showData % Method of GRENAT class
updateGrad % Method of GRENAT class
updateResp % Method of GRENAT class
updateSampling % Method of GRENAT class
initDirGRENAT % Initialization of the directories (MATLAB's path)
BuildCI % function for building confidence intervals (CI)
InfillCrit % Compute infill criteria EI/WEI/LCB
critErrDisp % Compute error criteria and display
dispDate % Display date and time
saveDisp % save figure in file
initDisp % Initialization of display variables
initMeta % Initialization of the surrogate model
initNbPts % Function for calculating th right number of sample points for the reference grid
addSample % Method of KernMatrix class
showKernel % Method of KernMatrix class
KRG % class for kriging/cokriging metamodel
cv % Method of KRG class
showInfo % Method of KRG class
update % Method of KRG class
cv % Method of RBF class
showInfo % Method of RBF class
update % Method of RBF class
cv % Method of SVR class
showInfo % Method of SVR class
update % Method of SVR class
compute % Method of xLS class
showInfo % Method of xLS class
update % Method of xLS class
xLS % Class for least-squares surrogate model
EstimPara % Function for estimating hyperparameters
PrepIn % Preparation for Indirect Gradient-Enhanced Surrogate Models
definePara % definition of the hyperparameters bounds (for estimation) or values (w/o estimation)
check % Method of MissData class
removeGM % Method of MissData class
removeGRM % Method of MissData class
removeGRV % Method of MissData class
removeGV % Method of MissData class
removeRM % Method of MissData class
removeRV % Method of MissData class
show % Method of MissData class
NormG % Method of NormRenorm class
choiceData % Method of NormRenorm class
computeNorm % Method of NormRenorm class
reNormG % Method of NormRenorm class
reNormVar % Method of NormRenorm class
checkRun % Static method of execParallel class
execParallel % Script for starting & stopping workers (parallel)
start % Method of execParallel class
stop % Method of execParallel class
buildDisp % Build space for plotting 1D/2D function
checkInterpRG %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
dispTableTwoColumns % Function display table with two columns (first must be text)
dispTxtOnOff % Function to display information depending on a boolean
evalFunGrad % Evaluation of the function and the gradients
mesuTime % Script dedicated to the initialisation, the measure and the display of the spent time
textProgressbar % Text progess bar
SOURCE CODE
%% function for printing information on the command window (based on fprintf)
%% L. LAURENT -- 12/09/2016 -- luc.laurent@lecnam.net
%     GRENAT - GRadient ENhanced Approximation Toolbox
%     A toolbox for generating and exploiting gradient-enhanced surrogate models
%     Copyright (C) 2016-2017  Luc LAURENT <luc.laurent@lecnam.net>
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with this program.  If not, see <http://www.gnu.org/licenses/>.
function nbT = Gfprintf(varargin)
%adding text in front of the original text
txtAdd='GRENAT';
%check if the first argument is a double (corresponding to a file id)
if isa(varargin{1},'double')
    %argOk=varargin{2:end};
    %use the classical fprintf function
    nbT=fprintf(varargin{:});
else
    argOk=varargin;
    %convert all inputs to a string
    str = sprintf(argOk{:});
    %find new lines
    strSplit=regexp(str,'\n','split');
    % display text and adding new keyword
    nbT=0;
    for itS=1:numel(strSplit)
        if itS==numel(strSplit)&&isempty(strSplit{itS})
        else
            txtD=[ txtAdd ' | ' strSplit{itS}];
            nbytes=fprintf('%s',txtD);
            nbT=nbT+nbytes;
        end
        if itS<numel(strSplit)
            nbytes=fprintf('\n');
            nbT=nbT+nbytes;
        end
    end
end
end