Description of mesuTime
mesuTime
PURPOSE
% Script dedicated to the initiailisation, the measure and the display of the spent time
SYNOPSIS
function [tictoc_compt,tInit]=mesuTime(compteur,tps_init)
DESCRIPTION
% Script dedicated to the initiailisation, the measure and the display of the spent time
 L.LAURENT -- 15/05/2012 -- luc.laurent@lecnam.net
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ExampleUse1D Example of use of GRENAT without the sampling toolbox
ExampleUse2D % Example of use of GRENAT without the sampling toolbox
ExampleUseDOE % Example of use of the GRENAToolbox with the LMTir one
critErrDisp % Compute error criteria and display
initMeta % Initialization of the surrogate model
BuildMeta % function for building surrogate model
EstimPara % Function for estimating hyperparameters
EvalMeta % Evaluation of the surrogate model
KRGBuild % function for building kriging and cokriging surrogate model
KRGCV % Function for computing various Cross-Validation criteria for KRG/GKRG
RBFCV % Function for computing various Cross-Validation criteria for RBF/GRBF
buildDisp % Build space for plotting 2D function
evalFunGrad % Evaluation of the function and the gradients
SOURCE CODE
%% Script dedicated to the initiailisation, the measure and the display of the spent time
% L.LAURENT -- 15/05/2012 -- luc.laurent@lecnam.net
%     GRENAT - GRadient ENhanced Approximation Toolbox
%     A toolbox for generating and exploiting gradient-enhanced surrogate models
%     Copyright (C) 2016  Luc LAURENT <luc.laurent@lecnam.net>
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with this program.  If not, see <http://www.gnu.org/licenses/>.
function [tictoc_compt,tInit]=mesuTime(compteur,tps_init)
if nargin==0
    %initialization tic-toc count
    tictoc_compt=tic;
    %Measure initial CPU time
    tInit=cputime;
elseif nargin==2
    tElapsed=toc(compteur);
    tCPUElapsed=cputime-tps_init;
    fprintf(' - - - - - - - - - - - - - - - - - - - - \n')
    fprintf('  #### Time/CPU time (s): %4.2f s / %4.2f s\n',tElapsed,tCPUElapsed);
end