Description of initGRENAT
initGRENAT
PURPOSE
% Method of GRENAT class
SYNOPSIS
function initGRENAT(obj)
DESCRIPTION
% Method of GRENAT class
 L. LAURENT -- 26/06/2016 -- luc.laurent@lecnam.net
CROSS-REFERENCE INFORMATION
This function calls:
dispDate % Display date and time
initDisp % Initialization of display variables
initMeta % Initialization of the surrogate model
MissData % class for checking input data for finding missing information
NormRenorm % Normalization and renormalization of the Data (class version)
Gfprintf % function for printing information on the command window (based on fprintf)
This function is called by:
GRENAT % GRENAT class for manipulating gradient-enhanced metamodels
SOURCE CODE
%% Method of GRENAT class
% L. LAURENT -- 26/06/2016 -- luc.laurent@lecnam.net
%     GRENAT - GRadient ENhanced Approximation Toolbox
%     A toolbox for generating and exploiting gradient-enhanced surrogate models
%     Copyright (C) 2016-2017  Luc LAURENT <luc.laurent@lecnam.net>
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with this program.  If not, see <http://www.gnu.org/licenses/>.
%% Initialize GRENAT's class
% responses and gradients
% INPUTS:
% - none
% OUTPUTS:
% - none
function initGRENAT(obj)
%load descriptions of properties
obj.infoProp=obj.affectTxtProp;
%
Gfprintf('=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=\n');
Gfprintf('=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=\n');
Gfprintf(' Create GRENAT Object \n');
% the date and time
dispDate;
% load subclasses
obj.confMeta=initMeta;          % metamodel configuration
obj.confDisp=initDisp;          % display configuration
obj.miss=MissData;              % missing data
obj.norm=NormRenorm;            % normalization data (NormRenorm class)
end