Description of LSBuild
LSBuild
PURPOSE
% function for least-sqaures surrogate model
SYNOPSIS
function [ret]=LSBuild(samplingIn,respIn,gradIn,metaData,missData)
DESCRIPTION
% function for least-sqaures surrogate model
 LS: Least-Squares
 GLS: gradient-base Least Squares
 L. LAURENT -- 27/01/2017 -- luc.laurent@lecnam.net
CROSS-REFERENCE INFORMATION
This function calls:
MultiMono % Function for evaluating the monomial terms and builds matrix of regressors
Gfprintf % function for printing information on the command window (based on fprintf)
This function is called by:
BuildMeta % function for building surrogate model
SUBFUNCTIONS
function boolOut=dispTxtOnOff(boolIn,txtInTrue,txtInFalse,returnLine)
SOURCE CODE
%% function for least-sqaures surrogate model
% LS: Least-Squares
% GLS: gradient-base Least Squares
% L. LAURENT -- 27/01/2017 -- luc.laurent@lecnam.net
%     GRENAT - GRadient ENhanced Approximation Toolbox
%     A toolbox for generating and exploiting gradient-enhanced surrogate models
%     Copyright (C) 2016  Luc LAURENT <luc.laurent@lecnam.net>
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with this program.  If not, see <http://www.gnu.org/licenses/>.
function [ret]=LSBuild(samplingIn,respIn,gradIn,metaData,missData)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Display Building information
textd='++ Type: ';
textf='';
Gfprintf('\n%s\n',[textd 'Least-Squares ((G)LS)' textf]);
Gfprintf('>> Deg : %i \n',metaData.polyOrder);
%
if dispTxtOnOff(metaData.cv.on,'>> CV: ',[],true)
    dispTxtOnOff(metaData.cv.full,'>> Computation all CV criteria: ',[],true);
    dispTxtOnOff(metaData.cv.disp,'>> Show CV: ',[],true);
end
%
Gfprintf('\n');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Initialisation of the variables
%number of sample points
ns=size(respIn,1);
%number of design variables
np=size(samplingIn,2);
%check availability of the gradients
availGrad=~isempty(gradIn);
%check missing data
if isfield(metaData,'miss')
    missResp=metaData.miss.resp.on;
    missGrad=metaData.miss.grad.on;
    availGrad=(~metaData.miss.grad.all&&metaData.miss.grad.on)||(availGrad&&~metaData.miss.grad.on);
else
    metaData.miss.resp.on=false;
    metaData.miss.grad.on=false;
    missResp=missData.miss.resp.on;
    missGrad=metaData.miss.grad.on;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Responses and gradients at sample points
YY=respIn;
%remove missing response(s)
if missResp
    YY=YY(metaData.miss.resp.ixAvail);
end
if availGrad
    tmp=gradIn';
    der=tmp(:);
    %remove missing gradient(s)
    if missGrad
        der=der(missData.grad.ixAvailLine);
    end
    YY=vertcat(YY,der);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Building indexes system for building KRG/GKRG matrices
if availGrad
    sizeMatRc=(ns^2+ns)/2;
    sizeMatRa=np*(ns^2+ns)/2;
    sizeMatRi=np^2*(ns^2+ns)/2;
    iXmatrix=zeros(sizeMatRc,1);
    iXmatrixA=zeros(sizeMatRa,1);
    iXmatrixAb=zeros(sizeMatRa,1);
    iXmatrixI=zeros(sizeMatRi,1);
    iXdev=zeros(sizeMatRa,1);
    iXsampling=zeros(sizeMatRc,2);
    tmpList=zeros(sizeMatRc,np);
    tmpList(:)=1:sizeMatRc*np;
    ite=0;
    iteA=0;
    iteAb=0;
    pres=0;
    %table of indexes for inter-lengths (1), responses (1) and 1st
    %derivatives (2)
    for ii=1:ns
        ite=ite(end)+(1:(ns-ii+1));
        iXmatrix(ite)=(ns+1)*ii-ns:ii*ns;
        iXsampling(ite,:)=[ii(ones(ns-ii+1,1)) (ii:ns)'];
        iteAb=iteAb(end)+(1:((ns-ii+1)*np));
        debb=(ii-1)*np*ns+ii;
        finb=ns^2*np-(ns-ii);
        lib=debb:ns:finb;
        iXmatrixAb(iteAb)=lib;
        for jj=1:np
            iteA=iteA(end)+(1:(ns-ii+1));
            decal=(ii-1);
            deb=pres+decal;
            li=deb + (1:(ns-ii+1));
            iXmatrixA(iteA)=li;
            pres=li(end);
            liste_tmpB=reshape(tmpList',[],1);
            iXdev(iteA)=tmpList(ite,jj);
            iXdevb=liste_tmpB;
        end
    end
    %table of indexes for second derivatives
    a=zeros(ns*np,np);
    decal=0;
    precI=0;
    iteI=0;
    for ii=1:ns
        li=1:ns*np^2;
        a(:)=decal+li;
        decal=a(end);
        b=a';
        iteI=precI+(1:(np^2*(ns-(ii-1))));
        debb=(ii-1)*np^2+1;
        finb=np^2*ns;
        iteb=debb:finb;
        iXmatrixI(iteI)=b(iteb);
        precI=iteI(end);
    end
else
    %table of indexes for inter-lenghts  (1), responses (1)
    bmax=ns-1;
    iXmatrix=zeros(ns*(ns-1)/2,1);
    iXsampling=zeros(ns*(ns-1)/2,2);
    ite=0;
    for ii=1:bmax
        ite=ite(end)+(1:(ns-ii));
        iXmatrix(ite)=(ns+1)*ii-ns+1:ii*ns;
        iXsampling(ite,:)=[ii(ones(ns-ii,1)) (ii+1:ns)'];
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Build regression matrix (for the trend model)
%depending on the availability of the gradients
if ~availGrad
    valFunPoly=MultiMono(samplingIn,metaData.polyOrder);
    if missResp
        %remove missing response(s)
        valFunPoly=valFunPoly(metaData.miss.resp.ixAvail,:);
    end
else
    %gradient-based
    [MatX,MatDX]=MultiMono(samplingIn,metaData.polyOrder);
    nbMonomialTerms=size(MatX,2);
    if missResp||missGrad
        sizeResp=ns-missData.resp.nb;
        sizeGrad=ns*np-missData.grad.nb;
        sizeTotal=sizeResp+sizeGrad;
    else
        sizeResp=ns;
        sizeGrad=ns*np;
        sizeTotal=sizeResp+sizeGrad;
    end
    %initialize regression matrix
    valFunPoly=zeros(sizeTotal,nbMonomialTerms);
    if missResp
        %remove missing response(s)
        MatX=MatX(metaData.miss.resp.ixAvail,:);
    end
    %load monomial terms of the polynomial regression
    valFunPoly(1:sizeResp,:)=MatX;
    if missGrad
        %remove missing gradient(s)
        MatDX=MatDX(missData.grad.ixt_dispo_line,:);
    end
    %add derivatives to the regression matrix
    valFunPoly(sizeResp+1:end,:)=MatDX;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%determine regressors
fct=valFunPoly'*valFunPoly;
fcY=valFunPoly'*YY;
if condest(fct)>1e15
    beta=pinv(fct)*fcY;
else
    beta=fct\fcY;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%store variables
ret.used.sampling=samplingIn;
ret.used.resp=respIn;
ret.used.availGrad=availGrad;
ret.used.grad=gradIn;
ret.used.np=np;
ret.used.ns=ns;
ret.ix.matrix=iXmatrix;
ret.ix.sampling=iXsampling;
ret.build.fct=valFunPoly;
ret.build.fc=valFunPoly';
ret.build.beta=beta;
ret.build.sizeFc=size(valFunPoly,2);
ret.build.y=YY;
ret.build.polyOrder=metaData.polyOrder;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Cross-validation (compute various errors)
if metaData.cv.on
    %countTime=mesuTime;
    Gfprintf(' > Computation CV\n');
%    [ret.build.cv]=LSCV(ret,metaData);
    %countTime.stop;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if availGrad;txt='GLS';else txt='LS';end
Gfprintf('\n >> END Building %s\n',txt);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end
%% function for display information
function boolOut=dispTxtOnOff(boolIn,txtInTrue,txtInFalse,returnLine)
boolOut=boolIn;
if nargin==2
    txtInFalse=[];
    returnLine=false;
elseif nargin==3
    returnLine=false;
end
if isempty(txtInFalse)
    Gfprintf('%s',txtInTrue);if boolIn; fprintf('Yes');else fprintf('No');end
else
    if boolIn; fprintf('%s',txtInTrue);else fprintf('%s',txtInFalse);end
end
if returnLine
    fprintf('\n');
end
end