Description of norm_denorm_g
norm_denorm_g
PURPOSE
% fonction assurant la normalisation/denormalisation des donnees de type gradients
SYNOPSIS
function [out]=norm_denorm_g(in,type,infos)
DESCRIPTION
% fonction assurant la normalisation/denormalisation des donnees de type gradients
% L. LAURENT -- 19/10/2011 -- laurent@lmt.ens-cachan.fr
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cross_validate_krg_ckrg % Fonction assurant le calcul de diverses erreurs par validation croisee dans le cas du Krigeage/CoKrigeage
cross_validate_rbf % Fonction assurant le calcul de diverses erreurs par validation croisee dans le cas RBF/GFRB
eval_krg_ckrg % Fonction assurant l'evaluation du metamodele de Krigeage ou de Cokrigeage
eval_rbf %fonction permettant d'evaluer le metamodele RBF en un ensemble de pts donnes
eval_swf %% Fonction assurant l'evaluation du metamodele 'Shepard Weighting Functions'
meta_krg_ckrg % fonction de construction des metamodeles de Krigeage et de Cokrigeage
meta_rbf %fonction permettant de construire un metamodele à l'aide de fonctions a
meta_swf %% Fonction assurant la préparation des données pour le metamodele 'Shepard Weighting Functions'
SOURCE CODE
%% fonction assurant la normalisation/denormalisation des donnees de type gradients
%% L. LAURENT -- 19/10/2011 -- laurent@lmt.ens-cachan.fr
function [out]=norm_denorm_g(in,type,infos)
% nombre d'echantillons
nbs=size(in,1);
% normalisation des donnees
if (nargin==3&&~isempty(infos.std_t))||nargin==2
    switch type
        case 'norm'
            std_t=infos.std_t;
            std_e=infos.std_e;
            out=in.*std_t(ones(nbs,1),:)./std_e;
        case 'denorm'
            std_t=infos.std_t;
            out=in*infos.std_e./std_t(ones(nbs,1),:);
        case 'denorm_concat'  %gradients concatenes en un vecteur colonne
            correct=infos.std_e./infos.std_t;
            nbv=numel(infos.std_t);
            out=in.*repmat(correct(:),nbs/nbv,1);
        otherwise
            error('Mauvais type de normalisation/denormalisation (cf. norm_denorm_g.m)')
    end
else
    out=in;
end