/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InformationFrame.java
 *
 * Created on Jul 24, 2009, 6:07:21 PM
 */

package ibbt.sumo.gui.forms;

import ibbt.sumo.gui.context.ConfigElement;

/**
 *
 * @author theking
 */
public class InformationFrame extends javax.swing.JDialog {
    private ConfigElement confEl;

    /** Creates new form InformationFrame */
    public InformationFrame(ConfigElement ce) {
        initComponents();
        this.confEl = ce;
        initInformationFrame();
    }

    private void initInformationFrame() {
        this.configNameLabel.setText(this.confEl.getName());
        this.configIdLabel.setText(this.confEl.getId());
        this.typeValueLabel.setText(this.confEl.getType());
        if (this.confEl.getDescription() == null || this.confEl.getDescription().equals(""))
            this.infoText.setText("No documentation available");
        else
            this.infoText.setText(this.confEl.getDescription());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descriptionLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        configNameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        configIdLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        descriptionPane = new javax.swing.JScrollPane();
        infoText = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();
        typeValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        descriptionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibbt/sumo/gui/inputfiles/sumo1.png"))); // NOI18N
        descriptionLabel.setText("Information about the selected configuration element.");

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        nameLabel.setText("Name:");

        configNameLabel.setText("name");

        idLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        idLabel.setText("ID:");

        configIdLabel.setText("id");

        descriptionPane.setBackground(new java.awt.Color(238, 238, 238));
        descriptionPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        infoText.setBackground(new java.awt.Color(238, 238, 238));
        infoText.setColumns(20);
        infoText.setEditable(false);
        infoText.setFont(new java.awt.Font("Lucida Grande", 2, 13));
        infoText.setForeground(new java.awt.Color(0, 0, 255));
        infoText.setLineWrap(true);
        infoText.setRows(5);
        descriptionPane.setViewportView(infoText);

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibbt/sumo/gui/inputfiles/ok_icon.gif"))); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(okButton);

        typeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        typeLabel.setText("Type:");

        typeValueLabel.setText("type");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, buttonPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                    .add(descriptionPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(nameLabel)
                        .add(18, 18, 18)
                        .add(configNameLabel)
                        .add(18, 18, 18)
                        .add(idLabel)
                        .add(18, 18, 18)
                        .add(configIdLabel)
                        .add(18, 18, 18)
                        .add(typeLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(typeValueLabel))
                    .add(descriptionLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(descriptionLabel)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(nameLabel)
                    .add(configNameLabel)
                    .add(idLabel)
                    .add(configIdLabel)
                    .add(typeLabel)
                    .add(typeValueLabel))
                .add(1, 1, 1)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(descriptionPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel configIdLabel;
    private javax.swing.JLabel configNameLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionPane;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextArea infoText;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeValueLabel;
    // End of variables declaration//GEN-END:variables



}
