/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on Jul 8, 2009, 12:58:08 PM
 */

package ibbt.sumo.gui.forms;

import ibbt.sumo.gui.context.ConfigXMLFile;
import ibbt.sumo.gui.context.DefaultXMLFile;
import ibbt.sumo.gui.context.Settings;
import ibbt.sumo.gui.context.SimulatorXMLFile;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;

import javax.imageio.ImageIO;

/**
 *
 * @author Sasa Berberovic
 */
public class MainForm extends javax.swing.JFrame {
    private String simPath = "";
    private String defaultPath = "";
    
    /**
     *
     */
    public MainForm() {
        initComponents();

        BufferedImage image = null;
        try {
            image = ImageIO.read(this.getClass().getResourceAsStream("/ibbt/sumo/gui/inputfiles/sumo.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        this.setIconImage(image);

        Settings settings = new Settings();
        settings.load();
        if (settings.useDefaultXMLPath()){
            this.defaultPath = settings.getDefaultXMLPath();
        }
        
    }

    /**
     *
     * @param path
     */
    public void setDefaultPath(String path){
        this.defaultPath = path;
    }
    

     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel(){
            @Override
            public void paint(Graphics g){
                BufferedImage img = null;
                try {
                    img = ImageIO.read(this.getClass().getResourceAsStream("/ibbt/sumo/gui/inputfiles/sumo.png"));
                } catch (IOException e) {
                }

                g.drawImage(img, 0, 0, this);
            }
        }
        ;
        infoPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        version = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        website = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newConfigFile = new javax.swing.JMenuItem();
        editConfigFile = new javax.swing.JMenuItem();
        setSettings = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUMO Configuration Creator");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setResizable(false);

        imagePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        imagePanel.setMaximumSize(new java.awt.Dimension(266, 361));
        imagePanel.setMinimumSize(new java.awt.Dimension(266, 361));
        imagePanel.setPreferredSize(new java.awt.Dimension(266, 361));

        org.jdesktop.layout.GroupLayout imagePanelLayout = new org.jdesktop.layout.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 262, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 357, Short.MAX_VALUE)
        );

        infoPanel.setLayout(new javax.swing.BoxLayout(infoPanel, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18));
        jLabel1.setText("SUMO Configuration Creator");
        jLabel1.setAlignmentX(Component.CENTER_ALIGNMENT);
        jPanel5.add(jLabel1);

        infoPanel.add(jPanel5);

        version.setText("Version 1.0 (beta)");
        version.setAlignmentX(Component.CENTER_ALIGNMENT);
        jPanel4.add(version);

        infoPanel.add(jPanel4);

        jPanel1.setAlignmentX(Component.CENTER_ALIGNMENT);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 10));
        jLabel5.setText("email:");
        jPanel1.add(jLabel5);

        email.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        email.setText("sumo@intec.ugent.be");
        jPanel1.add(email);

        infoPanel.add(jPanel1);

        jPanel2.setAlignmentX(Component.CENTER_ALIGNMENT);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 10));
        jLabel6.setText("website:");
        jPanel2.add(jLabel6);

        website.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        website.setText("http://www.sumowiki.intec.ugent.be/");
        jPanel2.add(website);

        infoPanel.add(jPanel2);

        jMenu1.setText("File");

        newConfigFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newConfigFile.setText("Open simulator file...");
        newConfigFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newConfigFileActionPerformed(evt);
            }
        });
        jMenu1.add(newConfigFile);

        editConfigFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        editConfigFile.setText("Edit existing config file...");
        editConfigFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editConfigFileActionPerformed(evt);
            }
        });
        jMenu1.add(editConfigFile);

        setSettings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        setSettings.setText("Settings...");
        setSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSettingsActionPerformed(evt);
            }
        });
        jMenu1.add(setSettings);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(imagePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 266, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(infoPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                .add(imagePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 361, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(infoPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void newConfigFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newConfigFileActionPerformed
        DefaultXMLFile defXML = new DefaultXMLFile();
        if (this.defaultPath.equals("")){
            if (!defXML.load()){
            	  SettingsFrame settings = new SettingsFrame(this, this.defaultPath);
                  settings.setModal(true);
                  settings.setVisible(true);
                  
                  this.defaultPath = settings.getDefaultPath();
                  System.out.println("Default location set to: " + this.defaultPath);
            }
        }
        else{
            if (!defXML.load(this.defaultPath))
                return;
        }

        SimulatorXMLFile simXML = new SimulatorXMLFile(this.simPath);
        if (!simXML.load())
            return;
        this.simPath = simXML.filepath();
            
        NewConfigFileForm n = new NewConfigFileForm(defXML, simXML);
        n.setModal(true);
        if (this.defaultPath.equals(""))
            n.setTitle("Template: default.xml from jar" );
        else
            n.setTitle("Template: default.xml from " + "\"" + this.defaultPath + "\"");
        n.setVisible(true);
    }//GEN-LAST:event_newConfigFileActionPerformed

    private void editConfigFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editConfigFileActionPerformed
        ConfigXMLFile confXML = new ConfigXMLFile();
        if (this.defaultPath.equals("")){
            if (!confXML.load())
                return;
            else
                confXML.prePorcessing();
        }
        else{
            if (!confXML.load(this.defaultPath))
                return;
            else
                confXML.prePorcessing();
        }
        
        NewConfigFileForm n = new NewConfigFileForm(confXML);
        n.setModal(true);
        if (this.defaultPath.equals(""))
            n.setTitle("Template: " + confXML.getFilename() + " and default.xml from jar" );
        else
            n.setTitle("Template: " + confXML.getFilename() + " and default.xml from " + "\"" + this.defaultPath + "\"");
        n.setVisible(true);
    }//GEN-LAST:event_editConfigFileActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void setSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSettingsActionPerformed
        SettingsFrame settings = new SettingsFrame(this, this.defaultPath);
        settings.setModal(true);
        settings.setVisible(true);
    }//GEN-LAST:event_setSettingsActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editConfigFile;
    private javax.swing.JLabel email;
    private javax.swing.JMenuItem exit;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newConfigFile;
    private javax.swing.JMenuItem setSettings;
    private javax.swing.JLabel version;
    private javax.swing.JLabel website;
    // End of variables declaration//GEN-END:variables

}
