/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RunElementPanel.java
 *
 * Created on Jul 9, 2009, 11:54:08 AM
 */

package ibbt.sumo.gui.forms;

import ibbt.sumo.gui.context.ConfigXMLFile;
import ibbt.sumo.gui.context.DefaultXMLFile;
import ibbt.sumo.gui.context.RunElement;
import ibbt.sumo.gui.context.SimulatorXMLFile;

/**
 *
 * @author theking
 */
public class RunElementPanel extends javax.swing.JPanel {
    private RunElementsTab parent;
    private RunElement run;
    private DefaultXMLFile defXML;
    private SimulatorXMLFile simXML;

    /** Creates new form RunElementPanel */
    public RunElementPanel(int index, RunElementsTab parent, DefaultXMLFile defXML, SimulatorXMLFile simXML) {
        this.parent = parent;
        this.defXML = defXML;
        this.simXML = simXML;
        this.run = new RunElement();

        initComponents();

        this.runLabel.setText("Run" + String.valueOf(index) + ": ");
        this.setName("Run" + String.valueOf(index));
    }

    public RunElementPanel(int index, RunElementsTab parent, RunElement run, ConfigXMLFile confXML) {
        this.parent = parent;
        this.defXML = confXML;
        this.simXML = confXML.getSimXMLFile();
        this.run = run;

        initComponents();
        initRunElementPanel(index);
    }

    public RunElement getRunElement(){
        this.run.setName(this.runName.getText());
        this.run.setRepititions((Integer) this.runRepeat.getValue());
        return this.run;
    }

    public void initRunElementPanel(int index) {
        this.runLabel.setText("Run" + String.valueOf(index) + ": ");
        this.setName("Run" + String.valueOf(index));
        this.runName.setText(this.run.getName());
        this.runRepeat.setValue(this.run.getRepititions());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        runLabel = new javax.swing.JLabel();
        runNameLabel = new javax.swing.JLabel();
        runName = new javax.swing.JTextField();
        runRepeat = new javax.swing.JSpinner();
        runRepeatLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        runLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        runLabel.setText("Run:");

        runNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        runNameLabel.setText("name:");

        runName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runNameActionPerformed(evt);
            }
        });

        runRepeat.setValue(1);

        runRepeatLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        runRepeatLabel.setText("repeat:");

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibbt/sumo/gui/inputfiles/edit_icon.png"))); // NOI18N
        editButton.setToolTipText("Edit run");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibbt/sumo/gui/inputfiles/delete_icon.gif"))); // NOI18N
        deleteButton.setToolTipText("Delete run");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(runLabel)
                .add(23, 23, 23)
                .add(runNameLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(runName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(runRepeatLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(runRepeat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(editButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(deleteButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(new java.awt.Component[] {deleteButton, editButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                .add(runLabel)
                .add(runName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(runRepeatLabel)
                .add(runNameLabel)
                .add(editButton)
                .add(runRepeat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(deleteButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void runNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runNameActionPerformed
        
    }//GEN-LAST:event_runNameActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        this.parent.removeRun(this);
        this.parent.reset();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        this.run.setName(this.runName.getText());
        this.run.setRepititions((Integer)this.runRepeat.getValue());
        
        SelectConfigElementsFrame sf = null;
        if (this.defXML instanceof ConfigXMLFile){
            ConfigXMLFile conf = (ConfigXMLFile) this.defXML;
            sf = new SelectConfigElementsFrame(conf, conf.getSimXMLFile(), this);
        }
        else{
            sf = new SelectConfigElementsFrame(this.defXML, this.simXML, this);
        }
        sf.setModal(true);
        sf.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel runLabel;
    private javax.swing.JTextField runName;
    private javax.swing.JLabel runNameLabel;
    private javax.swing.JSpinner runRepeat;
    private javax.swing.JLabel runRepeatLabel;
    // End of variables declaration//GEN-END:variables
}
