/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * simulatorPanel.java
 *
 * Created on Jul 9, 2009, 7:01:58 PM
 */

package ibbt.sumo.gui.forms;

import ibbt.sumo.gui.context.SimulatorXMLFile;

/**
 *
 * @author Sasa Berberovic
 */
public class SimulatorTab extends javax.swing.JPanel {
    private NewConfigFileForm parent;
    private SimulatorXMLFile simulator;

    /**
     *
     * @param parent
     */
    public SimulatorTab(NewConfigFileForm parent) {
        this.parent = parent;
        initComponents();
        initTab();
    }

    /**
     *
     * @param parent
     * @param simXML
     */
    public SimulatorTab(NewConfigFileForm parent, SimulatorXMLFile simXML) {
        this.parent = parent;
        this.simulator = simXML;
        initComponents();
        initTab();
    }

    /**
     *
     */
    public void initTab(){
        if (this.simulator != null){
            this.simulatorPath.setText(this.simulator.filepath());
            this.simulatorDescription.setText(this.simulator.simulatorDescription());
            this.openSimulatorButton.setEnabled(false);
        }
        else{
            this.simulatorPath.setText("Simulator not found!");
            this.simulatorDescription.setText("Simulator not found!");
            this.openSimulatorButton.setEnabled(true);
        }
    }

    /**
     *
     * @return
     */
    public String getSimulatorPath(){
        if (this.simulator != null)
            return this.simulator.filepath();
        else
            return "You have to load a simulator file!";
    }

    /**
     *
     * @return
     */
    public String getSimulatorName(){
        if (this.simulator != null)
            return this.simulator.filename();
        else
            return "You have to load a simulator file!";
    }

    /**
     *
     * @return
     */
    public SimulatorXMLFile getSimulatorFile(){
        return this.simulator;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadSimulatorButton = new javax.swing.JButton();
        loadSimulatorDialog_SimulatorDescrScrollPane = new javax.swing.JScrollPane();
        simulatorDescription = new javax.swing.JTextArea();
        simulatorPath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        openSimulatorButton = new javax.swing.JButton();

        loadSimulatorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibbt/sumo/gui/inputfiles/load_icon.gif"))); // NOI18N
        loadSimulatorButton.setText("Load ...");
        loadSimulatorButton.setEnabled(false);
        loadSimulatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSimulatorButtonActionPerformed(evt);
            }
        });

        setPreferredSize(new java.awt.Dimension(869, 490));

        simulatorDescription.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        simulatorDescription.setColumns(20);
        simulatorDescription.setRows(5);
        simulatorDescription.setText("You didn't load any simulator file yet!");
        loadSimulatorDialog_SimulatorDescrScrollPane.setViewportView(simulatorDescription);

        simulatorPath.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));

        jLabel1.setIcon(new javax.swing.ImageIcon("sumo.ico")); // NOI18N
        jLabel1.setText("Simulator location:");

        openSimulatorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibbt/sumo/gui/inputfiles/load_icon.gif"))); // NOI18N
        openSimulatorButton.setText("Open");
        openSimulatorButton.setEnabled(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(loadSimulatorDialog_SimulatorDescrScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(simulatorPath, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(openSimulatorButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(simulatorPath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(openSimulatorButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(loadSimulatorDialog_SimulatorDescrScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void loadSimulatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSimulatorButtonActionPerformed
        this.simulator = new SimulatorXMLFile("");
        if (this.simulator.load()){
            this.simulatorPath.setText(this.simulator.filepath());
            this.simulatorDescription.setText(this.simulator.simulatorDescription());
            this.openSimulatorButton.setEnabled(false);
        }
    }//GEN-LAST:event_loadSimulatorButtonActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loadSimulatorButton;
    private javax.swing.JScrollPane loadSimulatorDialog_SimulatorDescrScrollPane;
    private javax.swing.JButton openSimulatorButton;
    private javax.swing.JTextArea simulatorDescription;
    private javax.swing.JTextField simulatorPath;
    // End of variables declaration//GEN-END:variables

}
