/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlanTab_Simulator.java
 *
 * Created on Jul 10, 2009, 4:56:30 PM
 */

package ibbt.sumo.gui.forms;

/**
 *
 * @author Sasa Berberovic
 */
public class SimulatorElementPanel extends javax.swing.JPanel {
    public String path;


    /** Creates new form PlanTab_Simulator */
    public SimulatorElementPanel() {
        initComponents();
    }

    /**
     *
     * @param path
     */
    public void setPath(String path){
        this.path = path;
    }

    /**
     *
     * @param name
     */
    public void setName(String name){
        this.pathLabel.setText(name);
    }


    /**
     *
     * @return
     */
    public String getSimulatorName(){
        return this.simulatorLabel.getText();
    }

    /**
     *
     * @return
     */
    public String getSimulatorPath(){
        return this.path;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simulatorLabel = new javax.swing.JLabel();
        pathLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(651, 29));

        simulatorLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        simulatorLabel.setText("Simulator:");
        simulatorLabel.setPreferredSize(new java.awt.Dimension(67, 29));
        simulatorLabel.setRequestFocusEnabled(false);

        pathLabel.setText("path");
        pathLabel.setPreferredSize(new java.awt.Dimension(28, 29));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(simulatorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(39, 39, 39)
                .add(pathLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(pathLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(simulatorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pathLabel;
    private javax.swing.JLabel simulatorLabel;
    // End of variables declaration//GEN-END:variables

}
