Description of matlab2tikz
matlab2tikz
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
displaySurrogate % function for displaying response surfaces
AUTHORS
CHANGELOG
CONTRIBUTING
README
RBFBuild % Function for building Radial Basis Function surrogate model
SVRBuild % function for building gradient and non-gradient based SVR
SOURCE CODE
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "build_systems":
     [
        {
            "name": "CI tests (Octave)",
            "selector": "source.matlab",
            "working_dir": "${project_path}",
            "cmd":  ["./runtests.sh", "octave"]
        },
        {
            "name": "CI tests (MATLAB)",
            "selector": "source.matlab",
            "working_dir": "${project_path}",
            "cmd":  ["./runtests.sh", "matlab"]
        },
        {
            "name": "CI tests (MATLAB HG1)",
            "selector": "source.matlab",
            "working_dir": "${project_path}",
            "cmd":  ["./runtests.sh", "matlab-hg1"]
        },
        {
            "name": "CI tests (MATLAB HG2)",
            "selector": "source.matlab",
            "working_dir": "${project_path}",
            "cmd":  ["./runtests.sh", "matlab-hg2"]
        },
        {
            "name": "ACID: make",
            "working_dir": "${project_path}/test/tex",
            "cmd":  ["make","-j8"]
        },
        {
            "name": "ACID: distclean",
            "working_dir": "${project_path}/test/tex",
            "cmd":  ["make","distclean"]
        }
    ],
    "settings":
    {
        "FuzzyFilePath":{}
    }
}