function options = nsga2optimset()

%Return options with default values and return it when called with one output argument
options=struct('PopulationType', 'doubleVector', ...
               'PopInitRange', [0;1], ...
               'PopulationSize', 20, ...
			   'InitialPopulation',[], ...
			   'InitialScores', [], ...
               'Generations', 100, ...
			   'TimeLimit', Inf, ...
               'OutputFcn', [] );
		   
               %'EliteCount', 2, ...
               %'CrossoverFraction', 0.8, ...
               %'MigrationDirection','forward', ...
               %'MigrationInterval',20, ...
               %'MigrationFraction',0.2, ...
		   
			   
               %'FitnessLimit', -inf, ...
               %'StallGenLimit', 50, ...
               %'StallTimeLimit', 20, ...
               %'TolFun', 1e-6, ...
               %'TolCon', 1e-6, ...
               
               %'InitialScores', [], ...
               %'InitialPenalty', 10, ...
               %'PenaltyFactor', 100, ...
               %'PlotInterval',1, ...
               %'CreationFcn',@gacreationuniform, ...
               %'FitnessScalingFcn', @fitscalingrank, ...
               %'SelectionFcn', @selectionstochunif, ...
               %'CrossoverFcn',@crossoverscattered, ...
               %'MutationFcn',@mutationgaussian, ...
               %'HybridFcn',[], ...
               %'Display', 'final', ...
               %'PlotFcns', [], ...
               %'Vectorized','off', ...
			   %);   
