Description of rmae
rmae
PURPOSE
%fonction permettant le calcul de l'erreur RMAE
SYNOPSIS
function rmae=rmae(Zex,Zap)
DESCRIPTION
%fonction permettant le calcul de l'erreur RMAE
%L. LAURENT   --  22/03/2010   --  luc.laurent@ens-cachan.fr
CROSS-REFERENCE INFORMATION
This function calls:
rmae %fonction permettant le calcul de l'erreur RMAE
This function is called by:
crit_err % Calcul des criteres d'erreur et affichage
rmae %fonction permettant le calcul de l'erreur RMAE
SOURCE CODE
%%fonction permettant le calcul de l'erreur RMAE
%%L. LAURENT   --  22/03/2010   --  luc.laurent@ens-cachan.fr
% Jin 2000 "Comparative Studies Of Metamodeling Techniques under Multiple Modeling Criteria"
%%Zex: valeurs de la fonction objectif "exactes" obtenues par simulation
%%Zap: valeurs approchées de la fonction objectif obtenues par le
%%métamodèle
function rmae=rmae(Zex,Zap)
STD=std(Zap(:));
vec=abs(Zex-Zap);
rmae=max(vec(:))/STD;
end