Description of mono_total_random
mono_total_random
PURPOSE
*****************************************************************************80
SYNOPSIS
function [ x, rank, seed ] = mono_total_random (m, n, seed)
DESCRIPTION
*****************************************************************************80
% MONO_TOTAL_RANDOM: random monomial with total degree equal to N.
  Licensing:
    This code is distributed under the GNU LGPL license.
  Modified:
    09 September 2014
  Author:
    John Burkardt
  Parameters:
    Input, integer M, the spatial dimension.
    Input, integer N, the degree.
    0 <= N.
    Input, integer SEED, the random number seed.
    Output, integer X(M), the random monomial.
    Output, integer RANK, the rank of the monomial.
    Output, integer SEED, the updated random number seed.
CROSS-REFERENCE INFORMATION
This function calls:
i4_uniform_ab *****************************************************************************80
mono_unrank_grlex *****************************************************************************80
mono_upto_enum *****************************************************************************80
This function is called by:
mono_total_random_test *****************************************************************************80
SOURCE CODE
function [ x, rank, seed ] = mono_total_random (m, n, seed)
%*****************************************************************************80
%
%% MONO_TOTAL_RANDOM: random monomial with total degree equal to N.
%
%  Licensing:
%
%    This code is distributed under the GNU LGPL license.
%
%  Modified:
%
%    09 September 2014
%
%  Author:
%
%    John Burkardt
%
%  Parameters:
%
%    Input, integer M, the spatial dimension.
%
%    Input, integer N, the degree.
%    0 <= N.
%
%    Input, integer SEED, the random number seed.
%
%    Output, integer X(M), the random monomial.
%
%    Output, integer RANK, the rank of the monomial.
%
%    Output, integer SEED, the updated random number seed.
%
  rank_min = mono_upto_enum ( m, n - 1 ) + 1;
  rank_max = mono_upto_enum ( m, n );
  [ rank, seed ] = i4_uniform_ab ( rank_min, rank_max, seed );
  x = mono_unrank_grlex ( m, rank );
  return
end